catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('book/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    # re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
]

first_django_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
class Genre(models.Model):
    
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        return self.name

class Book(models.Model):

    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1001, help_text='Enter a brief description of the book')

    # isbn = models.CharField('ISBN', max_length=11, help_text='11 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])

    display_genre.short_description = 'Genre'

class BookInstance(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique id for the book")

    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)

    imprint = models.CharField(max_length=200)

    due_date = models.DateField(null=True, blank=True)

    loan_status = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=loan_status, blank=True, default='m', help_text="Book Availability")

    class Meta:
        ordering = ["due_date"]

    def __str__(self):
        # return f'{self.id} ({self.book.title})'
        return '{0} ({1})'.format(self.id, self.book.title)

class Author(models.Model):

    first_name = models.CharField(max_length=101)

    last_name = models.CharField(max_length=101)

    date_of_birth = models.DateField(null=True, blank=True)

    date_of_death = models.DateField('Died',null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):

    language_name = models.CharField(max_length=52, help_text="Enter language (e.g., English, Hindi, French, German, Spanish etc.)")

    def __str__(self):
        return self.language_name

catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def genre_list():
    return ', '.join(Genre.objects.values_list('name', flat=True))

@login_required
def index(request):
    num_books = Book.objects.all().count()

    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'genre_list': genre_list,
            'num_visits': num_visits
        }
    )

class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 5

    def get_queryset(self):
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['user_data'] = 'Additional data through generic class based view - BookListView in catalog/views.py'
        return context

class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book

class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 7

    def get_queryset(self):
        return Author.objects.all()

class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Document</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous"> {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-sm-2 bg-info">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li>
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'books' %}">All books</a>
                    </li>
                    <li>
                        <a href="{% url 'authors' %}">All authors</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
                {% endif %} 
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 bg-light p-4">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="row">
            {% block pagination %} 
                {% if is_paginated %}
                <div class="pagination mx-auto">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %} 
            {% endblock %}
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ author }}</h1>
    <div class="row">
        <div class="col"><strong>Date of birth : </strong>{% if author.date_of_birth %}{{author.date_of_birth}}{% else %}N/A{% endif %}</div>
        <div class="col"><strong>Date of death : </strong>{% if author.date_of_death %}{{author.date_of_death}}{% else %}N/A{% endif %}</div>
    </div>
    {% if author.book_set.all %}
    <p class="lead mt-4">Books by Author :</p>
    <ul>
        {% for book in author.book_set.all %}
            <li>
                <a class="text-info" href="{{ book.get_absolute_url }}">{{ book }}</a>
                <blockquote class="text-muted">{{ book.summary }}</blockquote>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p class="lead mt-5">Sorry, No books available for this author!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author list</h1>

    {% if author_list %}
    <ul>
        {% for author in author_list %}
            <li><a class="text-dark" href="{{ author.get_absolute_url }}">{{ author }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p class="lead">Sorry, no authors found!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div class="mt-2">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_date}}</p>{% endif %}
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a class="text-dark" href="{{ book.get_absolute_url }}">{{ book.title }}</a>
            ({{ book.author }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
<title>Library</title>
{% endblock %}

{% block content %}
    <h1>Local Library Home</h1>
    <p class="lead">Welcome to Local Library</p>

    <p>Book details : </p>
    <ul>
        <li>Books : {{ num_books }}</li>
        <li>Copies : {{ num_instances }}</li>
        <li>Copies available : {{ num_instances_available }}</li>
        <li>Authors : {{ num_authors }}</li>
        <li>Available Genres : {{ genre_list }}</li>
    </ul>
    <p>You've visited this page {{ num_visits }} times.</p>
{% endblock %}